[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/sovol/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing: True # Disable on low-powered device

[data_store]
temperature_store_size: 600
gcode_store_size: 1000

[announcements]
subscriptions:
    mainsail

[authorization]
trusted_clients:
    192.168.10.0/24
    192.168.42.0/24
    127.0.0.1/32

cors_domains:
    *.lan
    *.local
    *://localhost
    *://localhost:*
    *://my.mainsail.xyz
    *://app.fluidd.xyz
    *://mainsail.homeops.ca
    *://fluidd.homeops.ca
    *://pgcode.homeops.ca

[history]

[octoprint_compat]

[spoolman]
server: https://spoolman.homeops.ca

[timelapse]

[update_manager]
enable_auto_refresh: True
channel: dev
refresh_interval: 168

[update_manager mainsail-config]
type: git_repo
primary_branch: master
path: ~/mainsail-config
origin: https://github.com/mainsail-crew/mainsail-config.git
managed_services: klipper

[update_manager KlipperScreen]
type: git_repo
path: ~/KlipperScreen
origin: https://github.com/KlipperScreen/KlipperScreen.git
virtualenv: ~/.KlipperScreen-env
requirements: scripts/KlipperScreen-requirements.txt
system_dependencies: scripts/system-dependencies.json
managed_services: KlipperScreen

[update_manager crowsnest]
type: git_repo
path: ~/crowsnest
origin: https://github.com/mainsail-crew/crowsnest.git
primary_branch: v5
managed_services: crowsnest
system_dependencies: system-dependencies.json
virtualenv: ~/crowsnest-env
requirements: requirements.txt

[update_manager timelapse]
type: git_repo
primary_branch: main
path: ~/moonraker-timelapse
origin: https://github.com/mainsail-crew/moonraker-timelapse.git
managed_services: klipper moonraker

[update_manager spool2klipper]
type: git_repo
channel: dev
path: ~/spool2klipper
virtualenv: ~/spool2klipper/.venv
origin: https://github.com/bofh69/spool2klipper.git
primary_branch: main
requirements: requirements.txt
managed_services: spool2klipper
info_tags:
    desc=spool2klipper

[update_manager Klippain-ShakeTune]
type: git_repo
origin: https://github.com/Frix-x/klippain-shaketune.git
path: ~/klippain_shaketune
virtualenv: ~/klippy-env
requirements: requirements.txt
system_dependencies: system-dependencies.json
primary_branch: main
managed_services: klipper
[update_manager klipper-backup]
type: git_repo
path: ~/klipper-backup
origin: https://github.com/Staubgeborener/klipper-backup.git
managed_services: moonraker
primary_branch: main